apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webdemo
  name: webdemo
spec:
  containers:
  - image: nginx
    name: webdemo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
