apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-context-demo
  name: pod-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - image: ubuntu
    name: pod-context-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
