apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  labels:
    purpose: static-pvc-demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    kind: Managed
    diskName: static-pv
    diskURI: /subscriptions/fcee4d1c-aba2-4745-aef3-a103acb67ec1/resourcegroups/demos/providers/Microsoft.Compute/disks/demo-static-pv
  claimRef:
    namespace: demo
    name: data-store
