apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    # requests
    requests.cpu: "1"
    requests.memory: 1Gi
    # limits
    limits.cpu: "2"
    limits.memory: 2G
    # count
    configmaps: "10" 
    persistentvolumeclaims: "4" 
    replicationcontrollers: "20" 
    secrets: "10" 
    services: "10"