apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: static-pvc-demo
